name: docker

on:
  push:
    tags:
      - 'coco'

env:
  IMAGE_NAME: ghcr.io/mysteryengineer/reddit-downloader

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: vars
        run: |
          echo "VERSION=$(date +'%y.%-m.%-d')" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_NAME }},${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}