name: docker

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  schedule:
    - cron: '0 0 1 * *' # For more: https://crontab.guru

env:
  IMAGE_NAME: ghcr.io/mysteryengineer/reddit-downloader

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: vars
        run: |
          VERSION=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/tags" | jq -r '.[0].name')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_NAME }},${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}